language: ruby
rvm:
- 2.7.6
services:
  - mysql
branches:
  only:
    - master
    - qa
    - /quarter\d*/
    - develop
    - /2.\d*.\d*/
before_script:
- bundle update transam_core
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_transit_testing;" -uroot
- bundle config set without 'not_travis'
- gem install -v 2.3.4 bundler --document=
script:
- bundle exec rake app:transam_transit:prepare_rspec
- bundle exec rspec
