language: ruby
rvm:
- 2.2.2
branches:
  only:
  - /quarter\d*/
before_script:
- bundle update transam_core
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_transit_testing;" -uroot
script:
- bundle exec rake app:transam_transit:prepare_rspec
- bundle exec rspec
