language: ruby
rvm:
- 2.2.2
branches:
  only:
  - master
before_script:
- bundle update transam_core transam_spatial
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_transit_testing;" -uroot
script:
- bundle exec rake app:transam_transit:prepare_rspec_from_canon_schema
- bundle exec rspec
