language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
env:
- TEST_SUITE=rspec
- TEST_SUITE=cucumber
script:
- bundle exec rake app:transam_transit:prepare_rspec
- bundle exec $TEST_SUITE
before_install:
- openssl aes-256-cbc -K $encrypted_5d210218f793_key -iv $encrypted_5d210218f793_iv
  -in spec/dummy/db/schema.rb.enc -out spec/dummy/db/schema.rb -d
