language: ruby
rvm:
- 2.5.3
services:
  - mysql
branches:
  only:
    - master
    - /quarter\d*/
before_script:
- bundle update transam_core
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_transit_testing;" -uroot
script:
- bundle exec rake app:transam_transit:prepare_rspec
- bundle exec rspec
bundler_args: --without not_travis