language: ruby
rvm:
- 2.2.2
branches:
  only:
  - master
before_script:
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_transit_testing;" -uroot
- openssl aes-256-cbc -K $encrypted_4a6edbd8d703_key -iv $encrypted_4a6edbd8d703_iv
  -in spec/dummy/db/schema.rb.enc -out spec/dummy/db/schema.rb -d
script:
- bundle exec rake app:transam_transit:prepare_rspec
- bundle exec rspec
