#!/bin/bash

echo "Running script to check your view changes against other engines/apps. All TransAM repos must be in the same directory."

echo "======="
echo "The following files either shadow or are shadowed by your changes:"

files=`git status --porcelain | xargs -n1 basename | grep '\.haml\|erb$'`
for file in $files; do
  find .. -path "../$(basename "$PWD")" -prune -o -name $file -print
done

echo "======="