class CreateFacilityComponentTypes < ActiveRecord::DataMigration
  def up
    facility_component_types= [
        {name: 'Substructure', class_name: 'Facility', active:true},
        {name: 'Shell', class_name: 'Facility', active:true},
        {name: 'Interior', class_name: 'Facility', active:true},
        {name: 'Conveyance', class_name: 'Facility', active:true},
        {name: 'Plumbing', class_name: 'Facility', active:true},
        {name: 'HVAC', class_name: 'Facility', active:true},
        {name: 'Fire Protection', class_name: 'Facility', active:true},
        {name: 'Electrical', class_name: 'Facility', active:true},
        {name: 'Equipment / Fare Collection', class_name: 'Facility', active:true},
        {name: 'Site', class_name: 'Facility', active:true}
    ]

    facility_component_types.each do |type|
      ComponentType.create!(type)
    end

    facility_component_subtypes = [
        {name: 'Facilities - Walls', class_name: 'Facility', active:true},
        {name: 'Foundations - Columns', class_name: 'Facility', active:true},
        {name: 'Foundations - Pilings', class_name: 'Facility', active:true},
        {name: 'Basement - Materials', class_name: 'Facility', active:true},
        {name: 'Basement - Insulation', class_name: 'Facility', active:true},
        {name: 'Basement - Slab', class_name: 'Facility', active:true},
        {name: 'Basement - Floor Underpinnings', class_name: 'Facility', active:true},
        {name: 'Superstructure / Structural Frame - Columns', class_name: 'Facility', active:true},
        {name: 'Superstructure / Structural Frame - Pillars', class_name: 'Facility', active:true},
        {name: 'Superstructure / Structural Frame - Walls', class_name: 'Facility', active:true},
        {name: 'Roof - Surface', class_name: 'Facility', active:true},
        {name: 'Roof - Gutters', class_name: 'Facility', active:true},
        {name: 'Roof - Eaves', class_name: 'Facility', active:true},
        {name: 'Roof - Skylights', class_name: 'Facility', active:true},
        {name: 'Roof - Chimney Surrounds', class_name: 'Facility', active:true},
        {name: 'Exterior - Windows', class_name: 'Facility', active:true},
        {name: 'Exterior - Doors', class_name: 'Facility', active:true},
        {name: 'Exterior - Paint', class_name: 'Facility', active:true},
        {name: 'Exterior - Masonry', class_name: 'Facility', active:true},
        {name: 'Shell Appurtenances - Balconies', class_name: 'Facility', active:true},
        {name: 'Shell Appurtenances - Fire Escapes', class_name: 'Facility', active:true},
        {name: 'Shell Appurtenances - Gutters', class_name: 'Facility', active:true},
        {name: 'Shell Appurtenances - Downspouts', class_name: 'Facility', active:true},
        {name: 'Passenger Areas - Platform', class_name: 'Facility', active:true},
        {name: 'Passenger Areas - Access Tunnels / Passageways', class_name: 'Facility', active:true},
        {name: 'Partitions - Walls', class_name: 'Facility', active:true},
        {name: 'Partitions - Interior Doors', class_name: 'Facility', active:true},
        {name: 'Partitions - Fittings', class_name: 'Facility', active:true},
        {name: 'Partitions - Signage', class_name: 'Facility', active:true},
        {name: 'Stairs - Interior Stairs', class_name: 'Facility', active:true},
        {name: 'Stairs - Landings', class_name: 'Facility', active:true},
        {name: 'Finishes - Materials (walls)', class_name: 'Facility', active:true},
        {name: 'Finishes - Materials (floors)', class_name: 'Facility', active:true},
        {name: 'Finishes - Materials (ceilings)', class_name: 'Facility', active:true},
        {name: 'Finishes - Materials (all surfaces)', class_name: 'Facility', active:true},
        {name: 'Elevators', class_name: 'Facility', active:true},
        {name: 'Escalators', class_name: 'Facility', active:true},
        {name: 'Lifts (any type)', class_name: 'Facility', active:true},
        {name: 'Fixtures', class_name: 'Facility', active:true},
        {name: 'Water Distribution', class_name: 'Facility', active:true},
        {name: 'Sanitary Waste', class_name: 'Facility', active:true},
        {name: 'Rain Water Drainage', class_name: 'Facility', active:true},
        {name: 'Energy Supply', class_name: 'Facility', active:true},
        {name: 'Heat Generation and Distribution Systems', class_name: 'Facility', active:true},
        {name: 'Cooling Generation and Distribution Systems', class_name: 'Facility', active:true},
        {name: 'Testing, Balancing, Controls and Instrumentation', class_name: 'Facility', active:true},
        {name: 'Chimneys and Vents', class_name: 'Facility', active:true},
        {name: 'Sprinklers', class_name: 'Facility', active:true},
        {name: 'Standpipes', class_name: 'Facility', active:true},
        {name: 'Hydrants and Other Fire Protection Specialties', class_name: 'Facility', active:true},
        {name: 'Electrical Service & Distribution', class_name: 'Facility', active:true},
        {name: 'Lighting & Branch Wiring (Interior & Exterior)', class_name: 'Facility', active:true},
        {name: 'Communications & Security', class_name: 'Facility', active:true},
        {name: 'Lighting Protection', class_name: 'Facility', active:true},
        {name: 'Generators', class_name: 'Facility', active:true},
        {name: 'Emergency Lighting', class_name: 'Facility', active:true},
        {name: 'Maintenance & Service Equipment', class_name: 'Facility', active:true},
        {name: 'Turnstiles', class_name: 'Facility', active:true},
        {name: 'Ticket Machines', class_name: 'Facility', active:true},
        {name: 'Roadways / Driveways', class_name: 'Facility', active:true},
        {name: 'Roadways / Driveways - Signage', class_name: 'Facility', active:true},
        {name: 'Roadways / Driveways - Markings', class_name: 'Facility', active:true},
        {name: 'Roadways / Driveways - Equipment', class_name: 'Facility', active:true},
        {name: 'Parking Lots', class_name: 'Facility', active:true},
        {name: 'Parking Lots - Signage', class_name: 'Facility', active:true},
        {name: 'Parking Lots - Markings', class_name: 'Facility', active:true},
        {name: 'Parking Lots - Equipment', class_name: 'Facility', active:true},
        {name: 'Pedestrian Areas', class_name: 'Facility', active:true},
        {name: 'Pedestrian Areas - Signage', class_name: 'Facility', active:true},
        {name: 'Pedestrian Areas - Markings', class_name: 'Facility', active:true},
        {name: 'Pedestrian Areas - Equipment', class_name: 'Facility', active:true},
        {name: 'Site Development - Fences', class_name: 'Facility', active:true},
        {name: 'Site Development - Walls', class_name: 'Facility', active:true},
        {name: 'Site Development - Miscellaneous Structures', class_name: 'Facility', active:true},
        {name: 'Landscaping & Irrigation', class_name: 'Facility', active:true},
        {name: 'Site Utilities', class_name: 'Facility', active:true},
    ]

    facility_component_subtypes.each do |type|
      ComponentSubtype.create!(type)
    end
  end
end